version: '3.8'

services:
  my_project:
    build: .
    command: >
          sh -c "python manage.py migrate --noinput &&
                  python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0
