# Generated by Django 4.2.10 on 2025-06-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на товар"
            ),
        ),
    ]
